**Задание 1**

Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [3]:
import numpy as np

def creat_array(N):
    print(np.arange(0, N)[::-1])
    
creat_array(int(input('Введите число N: ')))

Введите число N: 15
[14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


**Задание 2**

Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [5]:
def sum_diag_matrix(N):
    diag_matrix = np.diag(np.arange(0, N)[::-1])
    print(diag_matrix)
    print('Сумма значений по диагонали:',np.trace(diag_matrix))

sum_diag_matrix(int(input('Введите число N: ')))

Введите число N: 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
Сумма значений по диагонали: 45


**Задание 3**

Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [25]:
from numpy import linalg
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )
b = np.array( [4, 12, -3] )

linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

**Задача 4**

Найдите самого похожего пользователя. Т. е. посчитайте косинусное расстояние между этим пользователем и всеми пользователями из массива user_stats

In [30]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    
    # длины векторов
    aLength = np.linalg.norm( a )
    bLength = np.linalg.norm( b )
    
    return np.dot( a, b ) / ( aLength * bLength )

In [31]:
nearest_user_stats_cos = 0
nearest_item_user = np.array([])
for item in users_stats:
    if cosine( next_user_stats, item ) > nearest_user_stats_cos:
        nearest_item_user = item

print('Самый похожий пользователь:',nearest_item_user)

Самый похожий пользователь: [0 1 1 0 0 0]
